Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.App
      CodeUri: /Users/sanderdemeester/Documents/coding/experiments/java/droppingprivileges/HelloWorldFunction
      Runtime: java11